project:
  type: website
  output-dir: "."
  render:
    - "index.qmd"

website:
  title: "Yanhao Wang"
  favicon: ""
  navbar: false
  google-analytics: "G-6BH5BCFHKP"
  search: false

format:
  html:
    theme: cosmo
    css: style.css
    toc: false
    code-tools: false
    html-math-method: mathjax
    page-layout: article
