---
---

<link rel="stylesheet" href="style.css" type="text/css">

* Something less depressing:
  + [第21期香樟经济学（北京）云Seminar：新冠肺炎疫情影响](https://mp.weixin.qq.com/s/uHiyYJdIzwF9e5omYPIDCQ)
  + [《发哨子的人》Stata版](https://mp.weixin.qq.com/s/OQgZZ0hOFPNC8-dHlE0jKw)
  + [美国检测和确诊数据可信吗？](https://mp.weixin.qq.com/s/fqQ-YIdqBZ9klaos2MOQtg)

&nbsp;  

* 从今天(3/15/2020, Sun)起，我开始记录关于疫情的消息，就当写日记。
  + 我在这里追踪案例数量: https://coronavirus.1point3acres.com
  + 我通过邮件和这里关注学校政策变化: https://coronavirus.iu.edu
  + 我还通过[WSJ](https://www.wsj.com), [NYTimes](https://www.nytimes.com)和[Bloomberg](https://www.bloomberg.com)的breaking news推送来关注最新情况发展，虽然这些媒体都很西方且在中国不受欢迎，但搜集信息不代表着盲目相信。

&nbsp; 
  
***Timeline*** (last updated: `r Sys.time()`)

* **Before 3/15/2020**
  + 疫情在美国多地爆发，学校停课，检测能力低下，医疗资源告急。川普宣布进入national emergency状态。美股大跌。
  + 总结的时候对欧洲的形势不太关心了，病毒乱杀，无药可救。
  
* **3/15/2020**
  + The Federal Reserve slashed its benchmark interest rate to near zero Sunday and said it would buy $700 billion in Treasury and mortgage-backed securities in an urgent response to the new coronavirus pandemic. 
  + IU将春假延长一周至3月底，同时将学期余下课程全部调至网课。IU Housing将关闭，学生原则上需要回到身份国或者自觅住处。部分学生有困难可以petition.
  
* **3/16/2020**
  + 周一开始，美股再次暴跌触发熔断，已经是疫情以来第三次，全天跌了约13%。
  + New Jersey带头开始curfew，但white house否认要全国curfew。讲真，curfew对遏制病毒传播是好事，但对社会经济影响也大，且容易激起逆反。
  + At least 6 bay area counties ordered to shelter-in-place.
  + 加拿大禁止非公民入境，美国公民暂时除外（有点搞笑，难道美国人现在不是最危险的之一么？）
  + 川普发推说COVID-19是Chinese Virus，继续甩锅，煽动仇恨，激起民愤！
  
* **3/17/2020**
  + 收到了IU Housing petition的邮件通知，花了很多时间跟老师同学沟通怎么写才能保证通过概率最大化。submit之后发现petition的人数比想象的多，做好了最坏的打算。
  + 川普呼吁各州自谋出路，各州黑人问号。

* **3/18/2020**
  + 油价和美股继续跌，下午再次触发熔断，三月以来第四次，和巴菲特的身价差距正快速减少。
  + A naval hospital ship is heading to NYC to help free 1000 beds for patients (美国版方舱).
  + The senate passed the House's coronavirus relief bill which will provide free testing, paid sick leave, food assistance and financial help.

* **3/19/2020**
  + 中国今天没有新增案例，全美单日新增超5000，确诊破万。意大利死亡人数超过中国。照此下去，美洲大陆再造一个意大利。
  + The Trump administration is asking states to delay releasing unemployment-claim numbers. 共和党邪教组织无疑。
  + 新闻说Monroe county有一例确诊，在IU health center就医，3/15就已经tested positive了，却一直没有出现在ISDH的统计里。稍晚时候，IU Health Bloomington又出来辟谣说这哥们儿不是Monroe county的。这些闹剧更加表明老美这些乱七八糟的统计口径和丢人的检测水平根本不能反映真实情况。病毒一直就在你身边。

* **3/20/2020**
  + 多州建议居民stay at home或者限制居民出行。Indiana和IU也有同样的要求，但最搞笑的是每次都是“保持现状until...”。停课也是，要停就停嘛，还“上到这周结束...”。一种后果就是造成大家在近期疯狂扎堆，混乱的预期管理使得政策效果适得其反。
  + U.S. extends individual tax fillig deadline from 4/15 to 7/15.
  + Monroe county health department爆出IU有学生在3/15就已经确诊（[报道](https://news.iu.edu/stories/2020/03/iu/releases/20-student-tests-positive-for-covid-19-coronavirus.html)），校长还一直发邮件说没有confirmed cases，说什么狗屁人间大爱同舟共济。一封啥信息量都没有的邮件，president发了provost转，provost转了dean转，完全无卵用。
  + 终于收到RPS邮件通知说可以继续留守校内公寓。
  
* **3/21/2020**
  + Trump Administration都是忙于出台各种各样刺激经济的政策，在遏制疫情方面毫无作为只会甩锅。
  

