---
---

<link rel="stylesheet" href="style.css" type="text/css">

### Working paper
**Competition and Countervailing Power: Evidence from China Eastern and Shanghai Airlines Merger**<br>
with Patrick McCarthy and Chun-Yu Ho<br>
June 2020, revised and resubmitted.

**What Happens Before New Banks Come to Town? Strategic Entry Deterrence in China’s Banking Market**<br>
May 2019.

**Banking Market Development and Consumption Risk Sharing: Evidence from China.**<br>
with Chun-Yu Ho, Dan Li and Peng Wang.<br> 
Nov 2017.

### Selected publication
Ho, Chun-Yu, McCarthy, Patrick, and **Wang, Yanhao** (2020). Decomposing Sources of Gain from Airline Mergers: A Model and Case Study from China. *Research in Transportation Economics*, 83.

**Wang, Yanhao** (2017). [Government-Firm Collusion, Environmental Regulation and Firm's Total Factor Productivity](https://oversea.cnki.net/KCMS/detail/detail.aspx?dbcode=CJFD&dbname=CJFDLAST2018&filename=JJLL201711007&v=yhAvitVXs%25mmd2Bz1TQLKwNKht8mCBW64t1cBbG6K8YAYpvzxPe%25mmd2BCGjtCCuJud840TYOm). *Economic Theory and Business Management*, 2017(11): 58-71 (in Chinese).

<!-- *For more writings and presentations, see my CV [here](files/CV_YanhaoWang_May2019.pdf).* -->